services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_DIALECT: mariadb
      DB_PORT: 3306
      DB_NAME: scubakeep
      DB_USER: scubakeep
      DB_PASSWORD: scubakeeppw

      BUCKET_HOST: minio
      BUCKET_PORT: 9000
      BUCKET_ACCESS_KEY: minioadmin
      BUCKET_ACCESS_SECRET: minioadminpw
      BUCKET_NAME: files
    ports:
      - "8080:8080"
    networks:
      - app
    depends_on:
      - db
      - minio

  db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: scubakeep
      MYSQL_USER: scubakeep
      MYSQL_PASSWORD: scubakeeppw
    ports:
      - "3306:3306"
    volumes:
      - scubakeep_mariadb_data:/var/lib/mysql
    networks:
      - app

  minio:
    image: bitnami/minio:2024
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpw
      MINIO_DEFAULT_BUCKETS: files
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - scubakeep_minio_data:/data
    networks:
      - app

volumes:
  scubakeep_mariadb_data:
  scubakeep_minio_data:

networks:
  app: